import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://selectorshub.com/xpath-practice-page/');
  await page.getByRole('link').nth(3).click();
  await page.locator('html').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Enter your company' }).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('textbox', { name: 'Country' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('meghana.mp.gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).fill('meghana.mp@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('abcd1234');
  await page.getByRole('textbox', { name: 'Enter your company' }).click();
  await page.getByRole('textbox', { name: 'Enter your company' }).fill('glocant');
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('7897990998');
  await page.getByRole('textbox', { name: 'Country' }).click();
  await page.getByRole('textbox', { name: 'Country' }).fill('india');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Enter your first crush name' }).click();
  await page.getByRole('textbox', { name: 'Enter your first crush name' }).fill('None');
  await page.getByText('User Email Password Company').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'DownLoad Link' }).click();
  const page1 = await page1Promise;
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'SelectorsHub Youtube Channel', exact: true }).click();
  const page2 = await page2Promise;
  await page2.goto('https://www.youtube.com/c/SelectorsHub');
  await page2.getByRole('button', { name: 'Cancel' }).click();
  await page2.getByRole('link', { name: 'Home', exact: true }).click();
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'A course with complex' }).click();
  const page3 = await page3Promise;
  await page3.getByRole('heading', { name: 'XPath, CSS Selector, Web,DOM' }).click();
  await page.getByRole('cell').first().click();
  await page.locator('#ohrmList_chkSelectRecord_16').check();
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Learning Hub' }).click();
  const page4 = await page4Promise;
  await page.getByRole('textbox', { name: 'user name field' }).click();
  await page.getByRole('textbox', { name: 'user name field' }).fill('dxfgdgg');
  await page.getByRole('textbox', { name: 'Enter pizza name' }).click();
  await page.getByRole('textbox', { name: 'Enter pizza name' }).fill('dfgfdg');
  await page.getByRole('textbox', { name: 'Enter pizza name' }).click();
  await page.locator('#concepts').dblclick();
  await page.locator('#userPass').click();
  await page.locator('#userPass').click();
  await page.locator('#userPass').click();
  await page.getByRole('link', { name: 'Click to practice iframe' }).click();
});